branches:
  only:
  - /^v[0-9]/

language: cpp

addons:
  artifacts:
    paths:
      - $(ls $TRAVIS_BUILD_DIR/*.bottle.tar.gz | tr "\n" ":")

env:
  global:
    - ARTIFACTS_BUCKET=homebrew-tap
    - ARTIFACTS_KEY=AKIAIWZQ3EMXPKKU5JZA
    # travis encrypt ARTIFACTS_SECRET=secret_password --add env.global
    - secure: nVTq9EEfTlNTDG4P4x3pmdroMUDkU2rOq0hs3MIqnpSQCFWNiiNRiAmCp3qTkC2zeme45xat6e+bhPnlU3NYPJ2cKitHhDtgizW82d6N1NVb9Fg6CcepvMZtZgeFjyiG9qr0IZNmBFV5PZ+6yFNL3v+FjpqUTYtLspf9kMdlSNuYv7cuKZWmXrkuMVidwZ+sRACSxTDVZbepNS/10OB5tO4sP9vZjZ7u2JDxb/jLBrJ/ZZ4vvZpQU7iq/yXmFvasNVlvqjDdhQEF4PsdgLjJn8u2KmQOrQtZjrrU7CEy6e3RPgb5mgguFMcRN5iigkzkWRUvcgClC6pYl6uBZjpKJh7Iy9IolqzTliW+dBuDsWkqLa5X17ILUpt5Lvad7mLEZsdbXPTA8CWNuSa6iY55tci3OM1PhRn5oz6+VFVFh7E4gS22x064SKewMK4gtbc4hx/QQO6o+mSQO+duERw0HZtC5ViUum6gNJeNyXqdMCgJrQJ/xEwq1iqcXWX3D3juf9t9yoJTBAr8pgsaFkIQxM61wPyj6R6a5jBG9v6IyVAaOXQxVchoF+d9iR9GWpakbUgVwW9vXLB+UNUv6tDdDm6rOt+wS1rMVyVe+dcNVe5DVKcJlEr4ikfIsZedzdmKaHLdUusaAkEekcZj2qhJ1iHOt4bWdIeASVpzMOPxhtM=

# (1) remember tu use 'brew cleanup -s' at the end of the travis script;
# otherwise, the $HOME/Library/Caches/Homebrew folder will be enormous
# (~2GB for the 4 jobs). This is because this folder is already present on
# osx images and it is big.
# (2) I also removed $HOME/.cache/Homebrew (cache of Linuxbrew) because it
# was also storing some logs, making the cache rebuilt every time.
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.gem/ruby"
    #- "$HOME/Library/Caches/Homebrew" # (1)
    #- "$HOME/.cache/Homebrew"        # (2)

matrix:
  include:
    # OS X 10.13 binaries
    - os: osx
      osx_image: xcode9.3beta
      env: OS=high_sierra-10.13

    # OS X 10.12 binaries
    - os: osx
      osx_image: xcode8.3
      env: OS=sierra-10.12

    # OS X 10.11 binaries
    - os: osx
      osx_image: xcode7.3
      env: OS=el_capitan-10.11

    # # OS X 10.10 binaries
    # - os: osx
    #   osx_image: xcode6.4
    #   env: OS=yosemite-10.10

    # Linux binaries
    - os: linux
      env: OS=x86_64_linux
      before_install:
        # Instal linuxbrew
        - export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH";
        # I added 'brew vendor-install ruby' because sometimes the install would
        # fail on 'Homebrew must be run under Ruby 2.3!' error.
        - yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" || (brew vendor-install ruby && brew update --force)
        # Fix a `brew doctor` error on "config" scripts for some reason
        - sudo rm -f /home/travis/.phpenv/shims/php-config
          /opt/pyenv/shims/*-config /usr/local/clang-*/bin/llvm-config
      before_cache:
        - brew cleanup

install:
  # 'brew doctor' must be run under HOMEBREW_DEVELOPER=1. Otherwise,
  # it returns 1 with the message "this osx version is outdated" on old osx ver.
  - HOMEBREW_DEVELOPER=1 brew doctor
  - brew tap Kronuz/tap
  - brew update

script:
  - brew install --build-bottle xapiand
  - brew bottle --no-rebuild xapiand
